services:
  webserver:
    image: php:8.4-apache # PHP inkl. Apache2-Webserver
    ports:
      - "8080:80"
    volumes: # lokales Volume mounten in /var/www/html
      - .:/var/www/html
    # Extensions mysqli und PDO installieren
    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
  
  db:
    image: mariadb # neueste Version von MariaDB
    restart: always
    environment: # ggf. Passwörter anpassen, aber dann auch unten bei phpmyadmin ändern!
      MYSQL_ROOT_PASSWORD: rootpasswort
      MYSQL_DATABASE: meine_db
      MYSQL_USER: benutzer
      MYSQL_PASSWORD: benutzerpasswort
    volumes: # persitente Speichern der Datenbank
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin # aktuelle Version
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpasswort

volumes:
  db_data: